# Generated by Django 3.2 on 2022-03-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccina', '0004_rename_date_of_birth_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Возраст'),
        ),
    ]
