# Generated by Django 3.2 on 2022-03-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccina', '0005_alter_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
    ]
